### ISSUE TITLE
Visualisation problems

### ISSUE THREAD

**Issue by Gabriele69** [fulvio999/unitConverter#1]
Hello, thank you for your work.
I wanted to report that using your app on small screens (example BQ 4.5) the texts overlap the icons and some writing is not displayed (look at the screeshot I have attached). They are small things to fix. Thank you!
![photo_2018-02-20_15-13-06](https://user-images.githubusercontent.com/17642335/36428587-97a8f614-1650-11e8-9ee0-7d30d09783b3.jpg)
![photo_2018-02-20_15-13-10](https://user-images.githubusercontent.com/17642335/36428588-97ccc184-1650-11e8-8638-9809299b7fc0.jpg)
![photo_2018-02-20_15-13-11](https://user-images.githubusercontent.com/17642335/36428589-97e73e38-1650-11e8-99b2-d55f931a35d8.jpg)
![photo_2018-02-20_15-13-13](https://user-images.githubusercontent.com/17642335/36428590-9801668c-1650-11e8-85ec-3a90bc69afe4.jpg)

**Comment by fulvio999** [comment]
fix released with version 1.3
